name: esthelogy_redesign
description: A personal Beauty Insights Concierge app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.5
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  photo_view: ^0.14.0
  lottie: ^2.2.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  go_router: ^6.0.1
  form_field_validator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment and add paths to your assets here when you have them:
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/

  # Uncomment and add font details here when you have custom fonts:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700